language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
    - tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C bin
    - export PATH=$(pwd)/bin:$PATH
script:
    - npm run test:unit
    - npm run test:module
deploy:
  - provider: netlify
    site: NETLIFY_SITE
    auth: NETLIFY_AUTH
    edge: true
  - provider: firebase
    token:
      secure: FIREBASE_TOKEN
